### ISSUE TITLE
Distance when define DORCs

### ISSUE THREAD

**Issue by dannihong** [buenrostrolab/stimATAC_analyses_code#4]
Hi,

Thanks for your great work. I wonder why you choose the widow as 50kb but not 100kb or 500kb. Does the window size influence the   results?

Thanks!

**Comment by vkartha** [comment]
Hi! Thank you for your interest. That's a good question, we looked at this in some of our previous work (https://www.sciencedirect.com/science/article/pii/S0092867420312538#sec2; see "Paired Measurements Associate Chromatin Peaks and Target Genes in cis") discussing the observed estimated half-lives of enhancer-TSS links to be ~24.4 kb. This was very similar to previous work assessing the effects of enhancers on gene expression using CRISPR perturbation by Gasperini et al (https://www.cell.com/cell/pdf/S0092-8674(18)31554-X.pdf ; see "Distance between Paired Enhancers and Promoters"), where they found it to be ~24 kb as well. Based on these concordant findings, we chose to pad each TSS by +/- 50 kb (so 100 kb around each gene TSS). The further out you go, while you may pick up more correlations, they are more likely to be false positives. 

Hope this helps!
