### ISSUE TITLE
When is subsetting by condition advised?

### ISSUE THREAD

**Issue by torkencz** [buenrostrolab/stimATAC_analyses_code#5]
Hi,

First of all, very cool tool. I was wondering at what stage of the analysis is it worth it to subset by conditions? E. g. I have condition "WT" and "MUT" and I want to discover the DORCs and TFs that are driving their difference (and are common between the two). In that case I would imagine running the RNA-ATAC pairing would be worth running within condition and then constructing the DORCs using the unified WT and MUT cell pairs (not separately on only MUT and only WT?). Afterwards should figR be run on the unified WT and MUT cells or separately?

**Comment by vkartha** [comment]
Hey! Thanks for your interest in our tool. I think you have it right there, essentially, the pairing you want to make sure you are not confounded by batch or genotype in anyway. So doing it within condition makes sense. If you were to pair across conditions, you'd be asking a slightly different question in that which "WT" cell most closely corresponds to the "MUT" cell in the other assay, which is interesting too, but different for your stated purposes. I would do what you mentioned, which is pair within, merge the paired ATAC (and RNA) for both conditions into a single dataset, and then run the gene-peak / TF-gene associations across all. What this will in theory let you do, is pick up associations that are either generally positive / negative (outside of WT vs MUT), or specific to a subpopulation (either a cell type, or a condition, like WT / MUT). Additionally, once you have the important genes (DORCs) and TFs, you can always compare the scores (TF motif score from chromVAR, or the DORC accessibility/RNA) for a given cell type between WT and MUT. Long answer short, we tend to run FigR across all the data in hopes that you can pick up both shared and specific effects (which we've showed with the stimulus PBMC dataset), but pair cells between assays within conditions first to avoid confounding factors that can change your interpretation
